### ISSUE TITLE
" pip install -r requirements.txt " not able to install all dependencies

### ISSUE THREAD

**Issue by bratin03** [dasabir/CS29006_SW_Lab_Spr2023#1]
# Unable to install decord

<img width="570" alt="Screenshot 2023-01-30 at 10 13 59 AM" src="https://user-images.githubusercontent.com/109758341/215389693-2c8de019-99af-4d27-9e89-1652b14214f8.png">

**Comment by harshith-chowdary** [comment]
For now, it can be done by removing the versions beside each package.
Also later there's some other issue saying "conflicting dependencies" where various packages require different versions of pytorch while the version of pytorch itself is not wrong in "requirements.txt".
So removing the versions for packages wherever it is causing an issue does the job but better wait for Sir's reply. I've sent a mail regarding this to Sir few days back and it will be reposted soon ig.

**Comment by dasabir** [comment]
The requirements.txt and the installation instructionis updated. Try these.
